### ISSUE TITLE
opening network setting turns out to general setting 

### ISSUE THREAD

**Issue by yanglongji** [guyromb/Cordova-open-native-settings#20]
as title..
in  ios 9.3.3

**Comment by guyromb** [comment]
does it happens also with the other settings?

**Comment by hannibaldinski** [comment]
Happens to all settings. See https://github.com/guyromb/Cordova-open-native-settings/issues/18

**Comment by timbru31** [comment]
It seems like that the published version from npm does not contain the following commit: https://github.com/guyromb/Cordova-open-native-settings/commit/ff240fa3b3e8a1a43788159a168fa69b62c7f537 - could you possibly publish an update @guyromb?

**Comment by guyromb** [comment]
@timbru31 can you make a pull request?

**Comment by timbru31** [comment]
I can't help you publish to npmjs.org - only you can do that ;)

**Comment by guyromb** [comment]
@timbru31 It is published, but I am not sure what the this commit is excluded
https://www.npmjs.com/package/cordova-open-native-settings

**Comment by timbru31** [comment]
The current version on npm is v1.4.1 which is equal to commit 8066c95f579eb36e53594c2f3bb37d8347c367d9 (from July 2017)

However there are two important commits for iOS since the latest release, which add support for more options: 3731a017d24034cd4cecf8591470adbee380ecb8 (for TouchID/PIN code) and ff240fa3b3e8a1a43788159a168fa69b62c7f537 (e.g. battery, keyboard, privacy)

- my question/request is: can you publish e.g. a v1.5.0 to npm?

**Comment by guyromb** [comment]
Published, can you confirm it is all updated now?

**Comment by timbru31** [comment]
Yes looks good! Thank you very much ❤️
