### ISSUE TITLE
iOS app gets rejected because of use of "prefs:root" or "App-Prefs:root" private API's.

### ISSUE THREAD

**Issue by Sandeep-Appster** [guyromb/Cordova-open-native-settings#33]
I have checked the code and found that plugin using the private API "prefs:root" way to open the setting app. Why we using this way?

Apple has given a very simple macro UIApplicationOpenSettingsURLString  to use that with simple openUrl function.

Please update the this plugin because it may cause others app to get rejected.

**Comment by Lenndev** [comment]
is this plugin updated already? cause my app was rejected because of this reason as well. In my case the cordova.plugins.diagnostic plugin also used this `@prefs:root`, i updated that plugin (cause i had an outdated version) and in the new source it wasn't present anymore... but i like to see it replaced in this one as well

**Comment by guyromb** [comment]
Duplicate https://github.com/guyromb/Cordova-open-native-settings/issues/36
